feature: adds continous randomly changing characters
andruuuh/matrix-effect pull request #1
Opened 2021-09-21 17:00 UTC by janDo-dev

2021-10-12 07:31 UTC, janDo-dev commented
@andruuuh was ist hier der Stand?

2021-11-04 12:23 UTC, andruuuh requested changes
sorry for taking this long to review.. ty anyway <3

2021-11-04 12:23 UTC, andruuuh commented on main.js
> +const w = 20;
warum hier oben und nicht unten, wie vorher, auskommentiert und leichter anpassbar?

2021-11-04 12:23 UTC, andruuuh commented on main.js
> +  // Change characters
<3 awesome

2021-11-04 14:31 UTC, janDo-dev commented on main.js
> +const w = 20;
Für mich zu dem Zeitpunkt übersichtlicher. 
Kann theoretisch auch wieder runter. Macht aber, abgesehen vom Scope, keinen Unterschied.

2024-01-26 18:33 UTC, closed without merging